---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-c=.yaml-lint.yml]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint-full
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: go-fmt-import
      - id: go-lint
      - id: go-err-check
      - id: go-static-check
      - id: go-unit-tests
      - id: gofumpt  # requires github.com/mvdan/gofumpt
      - id: go-ruleguard  # requires https://github.com/quasilyte/go-ruleguard
        args: [rules/rules.go]  # required
