name: pre-commit
on:
  push:
    branches: ["*"]
jobs:
  pre-commit:
    permissions: read-all
    runs-on: ubuntu-latest
    container:
      image: alpine:3.17
    steps:
      - name: Install job dependencies
        run: |
          apk add go python3-dev py3-pip git gcc musl-dev
          pip install pre-commit
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run pre-commit-hooks
        run: |
          git config --global --add safe.directory $PWD
          pre-commit run --all-files --color=always --show-diff-on-failure
