---
name: semantic-release
on:
  workflow_run:
    workflows: [pre-commit]
    types: [completed]
    branches: [master]
jobs:
  semantic-release:
    permissions:
      contents: write  # to be able to publish a GitHub release
      issues: write  # to be able to comment on released issues
      pull-requests: write  # to be able to comment on released pull requests
      id-token: write  # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine3.17
    env:
      NPM_CACHE_DIR: ~/.cache/npm
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install job dependencies
        run: apk add tar git
      - uses: actions/cache@v4
        with:
          path: ~/.cache
          key: semantic-release
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install semantic-release and plugins
        run: npm install --cache $NPM_CACHE_DIR
          semantic-release
          @semantic-release/github
          @semantic-release/changelog
          @semantic-release/git
          @semantic-release/exec
          conventional-changelog-conventionalcommits
      - name: Run semantic-release
        run: |
          git config --global --add safe.directory $PWD
          npx semantic-release
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSWORD: ${{ secrets.PASSPHRASE }}
